#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &
feh --bg-tile ~/Pictures/wallpapers/cross.png &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20
bspc config top_padding         20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus    true

bspc config focused_border_color            "#f4bf75"
bspc config normal_border_color             "#1d1f21"
bspc config urgent_border_color             "#ac4142"

bspc rule --add Gnome-calculator            state=floating
bspc rule --add libreoffice-startcenter     state=floating
bspc rule --add Org.gnome.Nautilus          state=floating
bspc rule --add Pavucontrol                 state=floating
bspc rule --add Gnome-system-monitor        state=floating
bspc rule --add Gedit                       state=floating
